### ISSUE TITLE
Initialization of OpenSSL

### ISSUE THREAD

**Issue by nmoinvaz** [kylehuff/buildcrx#5]
When trying to compile with OpenSSL on MSVC2008, I ran into an issue where the OpenSSL libraries were not initialized prior to calling PEM_read_RSAPrivateKey.

```
OpenSSL_add_all_algorithms();
OpenSSL_add_all_ciphers();
OpenSSL_add_all_digests();
```

Also take a look at this StackOverflow article:
http://stackoverflow.com/questions/16310457/failed-to-read-private-key-from-pem-file-in-c

**Comment by nmoinvaz** [comment]
The reason why I am recompiling in MSVC2008 was because the only binaries I could find crashed on Windows when I tried to launch them.

**Comment by kylehuff** [comment]
Commit in-bound!

I am curious as to why the binaries would not run for you. Which version of Windows? And when/where was it crashing (if you can tell)? Was there any meaningful output?

**Comment by nmoinvaz** [comment]
The first time I compiled it using MSVC2008 it didn't crash, so I didn't investigate any further. It had only given a standard Windows crash dialog which are usually worthless. I tried two executables, buildcrx.exe that I think was available through your website and buildcrx-v1.0.exe which was available through the Google repository which appears to be from 2011 -- and both crashed. I am on Windows 7 SP1 64-bit.

**Comment by kylehuff** [comment]
Okay, yeah, thanks for pointing out my failure to update the website...

There are some issues with that version, and in the [releases on this repo](https://github.com/kylehuff/buildcrx/releases) there are binaries for v0.2. I'm not saying v0.2 would behave any different, but at least I can point out that you are using an dated release.

Also, the version scheme at google code is wrong (besides out-dated). If the project management, repository and issues support were more like github, they would be current and correct! (in all truthfulness, I dislike code.google.com so much I forgot it was even out there.)

I'll make a note to update that project page as well.

**Comment by nmoinvaz** [comment]
I would just recommend nuking the Google code project that way people don't get confused. Most people use github.com for social coding anyways.

Nice work btw!
